In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Map_data.csv') 
df.head(2)

,Blank,CountDR,Incident Type DS,County,County Comma,Fiscal Year,URL,State,Country,Number of Records,...,Ia Program Declared,Id,Ih Program Declared,Incident Begin Date,Incident End Date,Incident Type,Last Refresh,Pa Program Declared,Place Code,State.Abbr
0,Disaster Number,1,floods,Santa Barbara County,"Santa Barbara County,",FY 1972,http://www.ready.gov/floods,California,United States,1,...,False,5d1bceb1d5b39c032f260b01,False,1/11/1972,1/11/1972,Flood,7/26/2019,True,99083,CA
1,Disaster Number,1,floods,Mendocino County,"Mendocino County,",FY 1974,http://www.ready.gov/floods,California,United States,1,...,False,5d1bceb2d5b39c032f2611ba,False,5/7/1974,5/7/1974,Flood,7/26/2019,True,99045,CA

In [3]:
df.isnull().sum()

Blank                          0
CountDR                        0
Incident Type DS             441
County                         0
County Comma                   0
Fiscal Year                    0
URL                          441
State                          0
Country                        0
Number of Records              0
PlaceHolder                    0
Declaration Date               0
declarationRequestNumber       0
Title                          0
declarationType                0
designatedArea                 0
disasterCloseoutDate        1318
Disaster Number                0
femaDeclarationString          0
fipsCountyCode                 0
fipsStateCode                  0
fyDeclared                     0
Hash                           0
Hm Program Declared            0
Ia Program Declared            0
Id                             0
Ih Program Declared            0
Incident Begin Date            0
Incident End Date            166
Incident Type                  0
Last Refresh                   0
Pa Program Declared            0
Place Code                     0
State.Abbr                     0
dtype: int64

In [4]:
pd.DataFrame(df.groupby('County')['Incident Type'].value_counts())

                                          Incident Type
County                   Incident Type
Alameda County           Severe Storm(s)              7
                         Flood                        5
                         Biological                   2
                         Fire                         2
                         Coastal Storm                1
...                                                 ...
Yuba County              Dam/Levee Break              1
                         Drought                      1
                         Freezing                     1
                         Hurricane                    1
Yurok Indian Reservation Fire                         1

[440 rows x 1 columns]

In [5]:
df['IncidentBeginDate'] = pd.to_datetime(df['Incident Begin Date'])

In [7]:
df['BeginMonth'] = df['IncidentBeginDate'].dt.month
df['BeginYear'] = df['IncidentBeginDate'].dt.year
df['BeginDay'] = df['IncidentBeginDate'].dt.day

In [8]:
disasters = df[(df['BeginYear'] >= 2010) & (df['Incident Type'] != 'Biological')][['Incident Type', 'County', 'BeginYear', 'BeginMonth']]
disasters.dropna(inplace = True)

In [9]:
disasters

        Incident Type                 County  BeginYear  BeginMonth
76    Dam/Levee Break           Butte County       2017           2
77    Dam/Levee Break          Sutter County       2017           2
78    Dam/Levee Break            Yuba County       2017           2
126        Earthquake            Kern County       2019           7
127        Earthquake  San Bernardino County       2019           7
...               ...                    ...        ...         ...
1324             Fire         Ventura County       2017          12
1325             Fire            Yuba County       2017          10
1326             Fire           Butte County       2018          11
1327             Fire     Los Angeles County       2018          11
1328             Fire         Ventura County       2018          11

[315 rows x 4 columns]

In [10]:
organized = pd.DataFrame({'count' : disasters.groupby( [ "County", 'BeginYear', 'BeginMonth', "Incident Type"] ).size()}).reset_index()
organized

             County  BeginYear  BeginMonth    Incident Type  count
0    Alameda County       2017           1            Flood      1
1    Alameda County       2017           1  Severe Storm(s)      1
2    Alameda County       2017           2            Flood      1
3     Alpine County       2017           2            Flood      1
4     Amador County       2015           9             Fire      1
..              ...        ...         ...              ...    ...
255     Yolo County       2019           2  Severe Storm(s)      1
256     Yuba County       2017           1  Severe Storm(s)      1
257     Yuba County       2017           2  Dam/Levee Break      1
258     Yuba County       2017           2            Flood      1
259     Yuba County       2017          10             Fire      2

[260 rows x 5 columns]

In [11]:
total = pd.DataFrame(organized.groupby(['County', 'BeginYear', 'BeginMonth', 'Incident Type'])[['count']].sum().sort_values(by = ['BeginYear', 'BeginMonth']))
total = total.reset_index()
#count represent 10 years of data
total['countperyear'] = total['count'] / 10
total

,County,BeginYear,BeginMonth,Incident Type,count,countperyear
0,Calaveras County,2010,1,Severe Storm(s),1,0.1
1,Imperial County,2010,1,Severe Storm(s),1,0.1
2,Los Angeles County,2010,1,Severe Storm(s),1,0.1
3,Riverside County,2010,1,Severe Storm(s),1,0.1
4,San Bernardino County,2010,1,Severe Storm(s),1,0.1
...,...,...,...,...,...,...
255,San Bernardino County,2019,10,Fire,1,0.1
256,Sonoma County,2019,10,Fire,1,0.1
257,Ventura County,2019,10,Fire,2,0.2
258,Santa Barbara County,2019,11,Fire,1,0.1
259,Ventura County,2019,11,Fire,1,0.1

In [13]:
total[(total['Incident Type'] == 'Fire')]

,County,BeginYear,BeginMonth,Incident Type,count,countperyear
7,Kern County,2010,7,Fire,2,0.2
8,Los Angeles County,2010,7,Fire,1,0.1
9,Kern County,2010,8,Fire,1,0.1
10,Kern County,2010,9,Fire,1,0.1
11,San Mateo County,2010,9,Fire,1,0.1
...,...,...,...,...,...,...
255,San Bernardino County,2019,10,Fire,1,0.1
256,Sonoma County,2019,10,Fire,1,0.1
257,Ventura County,2019,10,Fire,2,0.2
258,Santa Barbara County,2019,11,Fire,1,0.1
259,Ventura County,2019,11,Fire,1,0.1

In [ ]:
total.shape

In [ ]:
final = total[total['BeginMonth'].isin([5, 6, 7])]
final

In [ ]:
final.shape

In [ ]:
#per incident count per month taking into account 10 years
fi = pd.DataFrame({'count' : final.groupby( ['BeginMonth','County', "Incident Type"] ).size()}).reset_index()
fi.sort_values(['BeginMonth', 'County', 'count'], ascending = [True, True, False], inplace =True)
fi.head(60)

In [ ]:
fi[(fi['County'] == 'Mendocino County') & (fi['Incident Type'] == 'Fire')]

In [ ]:
#nationwide
national = organized.groupby(['BeginYear', 'BeginMonth', 'Incident Type'])[['count']].sum()
national.head(50)